const demoData = {
  categories: [
    { name: "Klip & styling", note: "Form, bevægelse og personlig rådgivning" },
    { name: "Farve & blond", note: "Balayage, highlights og nuancer" },
    { name: "Extensions", note: "Længde og fylde tilpasset dig" },
    { name: "Konsultation", note: "Når vi skal finde den rigtige plan sammen" }
  ],
  treatments: [
    { name:"Dameklip", category:"Klip & styling", duration:"60 min", price:"Demo fra 495 kr.", image:"https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=400&q=80" },
    { name:"Balayage", category:"Farve & blond", duration:"3–4 timer", price:"Demo fra 1.495 kr.", image:"https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=400&q=80" },
    { name:"Babylights", category:"Farve & blond", duration:"3 timer", price:"Demo fra 1.295 kr.", image:"https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=400&q=80" },
    { name:"Extensions", category:"Extensions", duration:"Efter konsultation", price:"Pris efter konsultation", image:"https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=400&q=80" },
    { name:"Farvekonsultation", category:"Konsultation", duration:"20 min", price:"Demo: gratis", image:"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=400&q=80" }
  ],
  customers: [
    {name:"Maria Jensen", initials:"MJ", treatment:"Balayage", last:"9 uger siden", next:"Klar til genbooking", status:"VIP"},
    {name:"Sofie Lund", initials:"SL", treatment:"Dameklip", last:"I dag", next:"Ny kunde", status:"Ny"},
    {name:"Anne Madsen", initials:"AM", treatment:"Gloss & styling", last:"8 uger siden", next:"Klar til genbooking", status:"Fast"},
    {name:"Nina Holm", initials:"NH", treatment:"Highlights", last:"10 uger siden", next:"Mangler opfølgning", status:"Fast"},
    {name:"Julie Petersen", initials:"JP", treatment:"Klip", last:"5 måneder siden", next:"Inaktiv", status:"Winback"}
  ]
};

const state = { mode:"public", bookingStep:0, booking:{category:"",treatment:"",customerType:"",hairLength:"",history:"",goal:"",date:"",time:"",name:"Maria Jensen",phone:"20 34 56 78",email:"maria@example.dk",note:""}, salonView:"today" };
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("is-visible");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("is-visible"),2200)}
function setMode(mode){state.mode=mode;$("#public-app").hidden=mode!=="public";$("#salon-app").hidden=mode!=="salon";$$(".mode-button").forEach(b=>b.classList.toggle("is-active",b.dataset.mode===mode));if(mode==="salon") renderSalon("today");window.scrollTo({top:0,behavior:"smooth"})}
$$(".mode-button").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));
$(".menu-toggle").addEventListener("click",e=>{const open=$(".public-nav").classList.toggle("is-open");e.currentTarget.setAttribute("aria-expanded",String(open))});
$$(".public-nav a").forEach(a=>a.addEventListener("click",()=>$(".public-nav").classList.remove("is-open")));
const range=$("#compare-range"),before=$("#before-layer"),handle=$("#compare-handle");
range.addEventListener("input",()=>{before.style.right=`${100-range.value}%`;handle.style.left=`${range.value}%`});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.12});
$$(".reveal").forEach(el=>observer.observe(el));

function openBooking(preselect=""){state.bookingStep=0;state.booking={...state.booking,category:"",treatment:preselect};if(preselect){const t=demoData.treatments.find(x=>x.name===preselect);if(t)state.booking.category=t.category}$("#booking-overlay").hidden=false;document.body.style.overflow="hidden";renderBooking()}
function closeBooking(){$("#booking-overlay").hidden=true;document.body.style.overflow=""}
$$("[data-start-booking]").forEach(b=>b.addEventListener("click",()=>openBooking()));
$$(".service-card").forEach(c=>c.addEventListener("click",()=>openBooking(c.dataset.service)));
$("#booking-close").addEventListener("click",closeBooking);
$("#booking-back").addEventListener("click",()=>{if(state.bookingStep===0)return closeBooking();state.bookingStep--;renderBooking()});
function nextBooking(){state.bookingStep++;renderBooking()}
function bookingFrame(title,lead,body,wide=false){return `<section class="booking-step ${wide?"":"narrow"}"><div class="step-meta"><span>Online booking</span><span>${state.bookingStep+1} / 8</span></div><h1>${title}</h1><p class="step-lead">${lead}</p>${body}</section>`}
function renderBooking(){
  $("#progress-fill").style.width=`${Math.min(100,((state.bookingStep+1)/8)*100)}%`;
  $("#booking-back").style.visibility=state.bookingStep>=7?"hidden":"visible";
  const b=state.booking;let html="";
  if(state.bookingStep===0){html=bookingFrame("Hvad ønsker du?","Vælg det område, der passer bedst. Vi hjælper dig med resten.",`<div class="choice-grid">${demoData.categories.map(c=>`<button class="choice" data-category="${c.name}"><strong>${c.name}</strong><small>${c.note}</small></button>`).join("")}</div>`)}
  if(state.bookingStep===1){const list=demoData.treatments.filter(t=>t.category===b.category||!b.category);html=bookingFrame("Vælg behandling","Priserne er demoeksempler og bekræftes altid før en rigtig booking.",list.map(t=>`<button class="treatment-choice" data-treatment="${t.name}"><img src="${t.image}" alt=""><div><strong>${t.name}</strong><p>${t.duration}</p></div><span>${t.price}<br>→</span></button>`).join(""),true)}
  if(state.bookingStep===2){html=bookingFrame("Har du været her før?","Det hjælper os med at forberede besøget bedst muligt.",`<div class="choice-grid"><button class="choice" data-customer-type="Ny kunde"><strong>Ny kunde</strong><small>Det er mit første besøg</small></button><button class="choice" data-customer-type="Eksisterende kunde"><strong>Eksisterende kunde</strong><small>Jeg har været hos Super Cut før</small></button></div>`)}
  if(state.bookingStep===3){html=bookingFrame("Fortæl lidt om dit hår","Kun det nødvendige — så rådgivningen kan starte allerede før besøget.",`<div class="form-grid"><div class="field"><label for="hairLength">Hårlængde</label><select id="hairLength"><option>Kort</option><option selected>Til skuldrene</option><option>Langt</option></select></div><div class="field"><label for="history">Tidligere farve</label><select id="history"><option>Ikke farvet</option><option selected>Farvet inden for 12 måneder</option><option>Ved ikke</option></select></div><div class="field full"><label for="goal">Hvad drømmer du om?</label><textarea id="goal" rows="3" placeholder="Fx et blødere, lysere resultat med naturlig udgroning"></textarea></div><div class="field full"><div class="upload-card">＋<br><strong>Tilføj et billede</strong><br><small>Simuleret upload i konceptdemoen</small></div></div></div><div class="booking-actions"><button class="button button-dark" id="continue-questions">Fortsæt</button></div>`,true)}
  if(state.bookingStep===4){const dates=[["I dag","23"],["Fre","24"],["Lør","25"],["Man","27"],["Tir","28"],["Ons","29"]];html=bookingFrame("Vælg en dag","Vi viser kun tider, der passer til behandlingens varighed.",`<div class="date-row">${dates.map(d=>`<button class="date-card ${b.date===d.join(" ")?"is-selected":""}" data-date="${d.join(" ")}"><small>${d[0]}</small><strong>${d[1]}</strong><small>jul</small></button>`).join("")}</div>`)}
  if(state.bookingStep===5){html=bookingFrame("Vælg tidspunkt",`${b.date||"Den valgte dag"} · ${b.treatment}`,`<div class="time-grid">${["09.30","11.00","13.30","15.00","16.30"].map(t=>`<button class="time-card ${b.time===t?"is-selected":""}" data-time="${t}">${t}</button>`).join("")}</div>`)}
  if(state.bookingStep===6){html=bookingFrame("Dine oplysninger","Så kan Super Cut bekræfte tiden og sende en påmindelse.",`<div class="form-grid"><div class="field full"><label for="name">Navn</label><input id="name" value="${b.name}"></div><div class="field"><label for="phone">Mobilnummer</label><input id="phone" value="${b.phone}"></div><div class="field"><label for="email">E-mail</label><input id="email" type="email" value="${b.email}"></div><div class="field full"><label for="note">Bemærkning (valgfri)</label><textarea id="note" rows="2"></textarea></div></div><div class="booking-actions"><button class="button button-dark" id="continue-details">Se booking</button></div>`,true)}
  if(state.bookingStep===7){html=bookingFrame("Er alt rigtigt?","Kontrollér din tid, før demo-bookingen bekræftes.",`<div class="summary-card"><div class="summary-row"><span>Behandling</span><strong>${b.treatment}</strong></div><div class="summary-row"><span>Dato og tid</span><strong>${b.date} · ${b.time}</strong></div><div class="summary-row"><span>Varighed</span><strong>${demoData.treatments.find(t=>t.name===b.treatment)?.duration||"Efter aftale"}</strong></div><div class="summary-row"><span>Pris</span><strong>${demoData.treatments.find(t=>t.name===b.treatment)?.price||"Efter aftale"}</strong></div><div class="summary-row"><span>Sted</span><strong>Falkoner Allé 112</strong></div></div><label class="terms"><input type="checkbox" id="terms"> Jeg accepterer demoens eksempelvilkår for afbud og booking.</label><div class="booking-actions"><button class="button button-dark" id="confirm-booking">Bekræft booking</button></div>`)}
  if(state.bookingStep===8){html=`<section class="booking-step confirmation"><div class="checkmark">✓</div><p class="eyebrow">Booking bekræftet</p><h1>Din tid er reserveret</h1><p class="step-lead">Vi glæder os til at se dig hos Super Cut.</p><div class="summary-card"><strong>${b.treatment}</strong><br>${b.date} kl. ${b.time}<br>Falkoner Allé 112</div><div class="sms-preview">Hej ${b.name.split(" ")[0]}. Din tid hos Super Cut er bekræftet ${b.date} kl. ${b.time}. Du modtager en påmindelse før dit besøg.</div><div class="hero-actions" style="justify-content:center"><button class="button button-dark" id="finish-booking">Til forsiden</button><button class="button button-outline" id="calendar-action">Føj til kalender</button></div></section>`}
  $("#booking-content").innerHTML=html;bindBookingActions()
}
function bindBookingActions(){
  $$("[data-category]").forEach(el=>el.addEventListener("click",()=>{state.booking.category=el.dataset.category;nextBooking()}));
  $$("[data-treatment]").forEach(el=>el.addEventListener("click",()=>{state.booking.treatment=el.dataset.treatment;nextBooking()}));
  $$("[data-customer-type]").forEach(el=>el.addEventListener("click",()=>{state.booking.customerType=el.dataset.customerType;nextBooking()}));
  $("#continue-questions")?.addEventListener("click",()=>{state.booking.hairLength=$("#hairLength").value;state.booking.history=$("#history").value;state.booking.goal=$("#goal").value;nextBooking()});
  $$("[data-date]").forEach(el=>el.addEventListener("click",()=>{state.booking.date=el.dataset.date;nextBooking()}));
  $$("[data-time]").forEach(el=>el.addEventListener("click",()=>{state.booking.time=el.dataset.time;nextBooking()}));
  $("#continue-details")?.addEventListener("click",()=>{state.booking.name=$("#name").value.trim()||"Maria";state.booking.phone=$("#phone").value;state.booking.email=$("#email").value;state.booking.note=$("#note").value;nextBooking()});
  $("#confirm-booking")?.addEventListener("click",()=>{if(!$("#terms").checked)return showToast("Acceptér eksempelvilkårene for at fortsætte");nextBooking()});
  $("#finish-booking")?.addEventListener("click",closeBooking);$("#calendar-action")?.addEventListener("click",()=>showToast("Kalenderinvitation klargjort · simulation"));
}

function renderSalon(view){state.salonView=view;$$(".salon-nav").forEach(b=>b.classList.toggle("is-active",b.dataset.view===view));const c=$("#salon-content");$("#view-kicker").textContent=view==="today"?"Torsdag · 23. juli":"Super Cut · Konceptdemo";c.innerHTML=view==="today"?todayView():view==="calendar"?calendarView():view==="customers"?customersView():view==="profile"?profileView():view==="followup"?followupView():futureView();bindSalonActions()}
function todayView(){return `<section class="salon-view"><div class="view-heading"><div><h1>Godmorgen, Valdeta</h1><p>Du har 6 kunder i dag. Den første kommer kl. 09.30.</p></div><button class="button button-dark" data-new-booking>＋ Opret booking</button></div><div class="metric-grid"><div class="metric"><span>Bookinger i dag</span><strong>6</strong></div><div class="metric"><span>Forventet omsætning</span><strong>4.850 kr.</strong></div><div class="metric"><span>Næste ledige tid</span><strong>14.30</strong></div><div class="metric"><span>No-shows denne måned</span><strong>1,8%</strong></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-heading"><h2>Dagens kalender</h2><button class="subtle-button" data-view-link="calendar">Se hele kalenderen</button></div>${appointments()}</div><div><div class="next-card"><p class="eyebrow">Næste kunde · om 27 min.</p><h2>Maria Jensen</h2><p>Balayage · ca. 3 timer</p><div class="customer-note">Foretrækker kølige beige toner. Sensitiv hovedbund. Brugte Olaplex sidst.</div><button class="button button-light" style="margin-top:24px" data-profile>Åbn kundeprofil</button></div><div class="followup-card"><p class="eyebrow">Smart opfølgning</p><h3>3 kunder er klar til genbooking</h3><button class="text-link" data-view-link="followup">Se forslag →</button></div></div></div></section>`}
function appointments(){return [["09.30","Maria Jensen","Balayage","Fast kunde"],["13.00","Sofie Lund","Dameklip","Ny kunde"],["14.30","Ledig tid","60 minutter","Åben"],["15.30","Anne Madsen","Gloss & styling","Fast kunde"]].map(a=>`<div class="appointment" data-appointment><span class="appointment-time">${a[0]}</span><div><strong>${a[1]}</strong><small>${a[2]}</small></div><span class="status">${a[3]}</span></div>`).join("")}
function calendarView(){const headers=["","Man 20","Tir 21","Ons 22","Tor 23","Fre 24"];let cells=headers.map(h=>`<div class="calendar-cell header">${h}</div>`).join("");for(let hour=9;hour<18;hour++){cells+=`<div class="calendar-cell header">${String(hour).padStart(2,"0")}.00</div>`;for(let d=1;d<=5;d++){const event=(hour===9&&d===4)?"Maria · Balayage":(hour===13&&d===4)?"Sofie · Klip":(hour===15&&d===4)?"Anne · Gloss":"";cells+=`<div class="calendar-cell">${event?`<button class="calendar-event" data-appointment>${event}</button>`:""}</div>`}}return `<section class="salon-view"><div class="view-heading"><div><h1>Kalender</h1><p>Uge 30 · 20.–24. juli</p></div><div class="calendar-toolbar"><button>Dag</button><button class="is-active">Uge</button><button data-new-booking>＋ Booking</button></div></div><div class="calendar-grid">${cells}</div></section>`}
function customersView(){return `<section class="salon-view"><div class="view-heading"><div><h1>Kunder</h1><p>Relationer, historik og næste gode handling.</p></div><button class="button button-dark">＋ Ny kunde</button></div><div class="customer-toolbar"><input class="search-input" id="customer-search" placeholder="Søg efter kunde"><button class="filter-chip is-active">Alle</button><button class="filter-chip">Nye</button><button class="filter-chip">Genbooking</button><button class="filter-chip">VIP</button></div><div class="customer-list" id="customer-list">${customerRows(demoData.customers)}</div></section>`}
function customerRows(list){return list.map(c=>`<div class="customer-row" data-customer="${c.name}"><div class="avatar">${c.initials}</div><strong>${c.name}</strong><span>${c.treatment}<br><small>${c.last}</small></span><span>${c.next}</span><span class="status">${c.status}</span></div>`).join("")}
function profileView(){return `<section class="salon-view"><button class="subtle-button" data-view-link="customers">← Tilbage til kunder</button><div class="profile-hero"><img class="profile-photo" src="https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=400&q=80" alt="Demoportræt af Maria"><div><p class="eyebrow">Kunde siden 2024</p><h1>Maria Jensen</h1><p>Fast kunde · besøger typisk hver 8. uge</p><div class="profile-tags"><span class="status">VIP</span><span class="status">Kølige toner</span><span class="status">Olaplex</span></div></div><div class="profile-actions"><button class="button button-outline">Send besked</button><button class="button button-dark" data-new-booking>Opret booking</button></div></div><div class="insight"><div><p class="eyebrow">Anbefalet næste handling</p><h2>Maria er én uge over sin normale besøgsrytme.</h2><p>En personlig besked nu gør det let at komme tilbage uden at virke påtrængende.</p></div><button class="button button-dark" data-send>Send genbooking</button></div><div class="profile-grid"><div class="panel"><div class="panel-heading"><h2>Behandlingshistorik</h2></div>${[["22. maj","Balayage","Kølig beige toner · Olaplex"],["28. mar.","Toner","Opfriskning og styling"],["30. jan.","Highlights","Fine highlights · lav developer"],["4. dec.","Klip","Spidser og face framing"]].map(x=>`<div class="timeline-item"><time>${x[0]}</time><div><strong>${x[1]}</strong><br><small>${x[2]}</small></div></div>`).join("")}</div><div class="panel"><div class="panel-heading"><h2>Det er godt at huske</h2></div><p><strong>Farvenoter</strong><br>Kølig beige toner. Undgå varme, gyldne nuancer. Medium developer.</p><p><strong>Hensyn</strong><br>Sensitiv hovedbund. Spørg ind før farve.</p><p><strong>Produkter</strong><br>Olaplex No. 3 og farvebevarende shampoo.</p><p><strong>Kontakt</strong><br>maria@example.dk · 20 34 56 78</p></div></div></section>`}
function followupView(){const cards=[["Maria Jensen","1 uge over normal rytme","Hej Maria. Det er nu cirka otte uger siden dit sidste besøg hos Super Cut. Skal jeg finde et par tider til din næste balayage?"],["Nina Holm","Highlights · 10 uger siden","Hej Nina. Skal vi finde en tid til at friske dine highlights op? Jeg sender gerne et par forslag."],["Anne Madsen","Gloss · klar til opfriskning","Hej Anne. Det er snart tid til en gloss-opfriskning. Vil du se de ledige tider i næste uge?"]];return `<section class="salon-view"><div class="view-heading"><div><h1>Opfølgning</h1><p>Personlige forslag baseret på kundernes besøg — aldrig massebeskeder.</p></div></div>${cards.map((x,i)=>`<div class="message-card" data-message-card><div><strong>${x[0]}</strong><p>${x[1]}</p></div><textarea aria-label="Besked til ${x[0]}">${x[2]}</textarea><button class="button button-dark" data-send>Send</button></div>`).join("")}<div class="panel"><div class="panel-heading"><h2>Automatiske beskeder</h2></div>${["Bookingbekræftelse","48-timers påmindelse","Tak for besøget","Anmodning om anmeldelse","Genbookingspåmindelse"].map(x=>`<div class="summary-row"><strong>${x}</strong><span class="status">Aktiv</span></div>`).join("")}</div></section>`}
function futureView(){const f=[["◷","Online booking","Kunder booker behandling og tid uden at afbryde salonen."],["◉","Bookinggaranti","Depositum på lange behandlinger kan reducere dyre udeblivelser."],["✉","Påmindelser","SMS og e-mail før besøget — kobles på i en rigtig version."],["★","Anmeldelser","Venlig opfølgning efter besøget og direkte link til Google."],["↗","Genbooking","Systemet hjælper tidligere kunder tilbage på det rigtige tidspunkt."],["⌁","Integrationer","Betaling, kalender og regnskab kan forbindes efter validering."]];return `<section class="salon-view"><div class="view-heading"><div><h1>Hvad kan Salon OS blive?</h1><p>Demoen viser oplevelsen. Disse moduler kan aktiveres i en produktionsversion.</p></div></div><div class="future-grid">${f.map(x=>`<article class="future-card"><div class="future-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><span class="status">Mulig integration</span></article>`).join("")}</div></section>`}
function bindSalonActions(){
  $$("[data-view-link]").forEach(b=>b.addEventListener("click",()=>renderSalon(b.dataset.viewLink)));
  $$("[data-profile]").forEach(b=>b.addEventListener("click",()=>renderSalon("profile")));
  $$("[data-customer]").forEach(b=>b.addEventListener("click",()=>b.dataset.customer==="Maria Jensen"?renderSalon("profile"):showToast(`${b.dataset.customer} åbnet · demo`)));
  $$("[data-send]").forEach(b=>b.addEventListener("click",()=>{b.textContent="Sendt ✓";b.disabled=true;showToast("Genbookingsbesked markeret som sendt")}));
  $$("[data-new-booking]").forEach(b=>b.addEventListener("click",()=>showToast("Ny manuel booking · simulation")));
  $$("[data-appointment]").forEach(b=>b.addEventListener("click",()=>showToast("Bookingdetalje åbnet · simulation")));
  $("#customer-search")?.addEventListener("input",e=>{$("#customer-list").innerHTML=customerRows(demoData.customers.filter(c=>c.name.toLowerCase().includes(e.target.value.toLowerCase())));bindSalonActions()});
}
$$(".salon-nav").forEach(b=>b.addEventListener("click",()=>renderSalon(b.dataset.view)));
renderSalon("today");
